/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 * For more detailed information on multi-project builds, please refer to https://docs.gradle.org/9.0.0/userguide/multi_project_builds.html in the Gradle documentation.
 */

plugins {
    // Apply the foojay-resolver plugin to allow automatic download of JDKs
    id("org.gradle.toolchains.foojay-resolver-convention") version "1.0.0"
}

rootProject.name = "kafka-example"
// include("app")

// 프로젝트의 모든 하위 모듈을 포함하도록 수정합니다.
include("apps:order")
include("apps:payment")
include("apps:inventory")
include("common") // 공통 DTO 등이 포함된 모듈로 추정됩니다.
