spring:
  datasource:
    url: jdbc:postgresql://postgres-order:5432/order
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
  sql:
    init:
      mode: always
